# Generated by Django 4.2.6 on 2024-01-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_rename_predresults_irispredresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeStylePredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emr_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
