# Generated by Django 4.2.6 on 2023-10-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date_added',
        ),
    ]
