# Generated by Django 4.2.6 on 2024-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_date_comment_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='temporary-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
